const {DynamoDBClient}=require('@aws-sdk/client-dynamodb');
const {DynamoDBDocumentClient,PutCommand}=require('@aws-sdk/lib-dynamodb');
const {S3Client,PutObjectCommand}=require('@aws-sdk/client-s3');
const {getSignedUrl}=require('@aws-sdk/s3-request-presigner');
const crypto=require('crypto');
const ddb=DynamoDBDocumentClient.from(new DynamoDBClient({}));
const s3=new S3Client({});
const maxFiles=Number(process.env.MAX_FILES||20),maxTotal=Number(process.env.MAX_TOTAL_SIZE||2147483648),maxFile=Number(process.env.MAX_FILE_SIZE||2147483648);
const headers=()=>({'Access-Control-Allow-Origin':process.env.ALLOWED_ORIGIN,'Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization','Content-Type':'application/json'});
const out=(s,b)=>({statusCode:s,headers:headers(),body:JSON.stringify(b)}),fail=(s,c,m)=>out(s,{success:false,error:{code:c,message:m}});
function validate(files){if(!Array.isArray(files)||files.length<1||files.length>maxFiles)throw[400,'INVALID_FILE_LIST',`Choose between 1 and ${maxFiles} files.`];let total=0;for(const f of files){if(!f||typeof f.fileName!=='string'||!f.fileName.trim()||f.fileName.length>255)throw[400,'INVALID_FILE_NAME','Invalid file name.'];if(!Number.isSafeInteger(f.fileSize)||f.fileSize<=0||f.fileSize>maxFile)throw[413,'FILE_TOO_LARGE','File exceeds the maximum size.'];if(typeof f.contentType!=='string'||f.contentType.length<1||f.contentType.length>200||!/^[\w.+-]+\/[\w.+-]+$/.test(f.contentType))throw[400,'INVALID_CONTENT_TYPE','Invalid content type.'];total+=f.fileSize;if(total>maxTotal)throw[413,'TOTAL_SIZE_TOO_LARGE','Total upload size exceeds the limit.'];}return total;}
exports.handler=async e=>{if(e?.requestContext?.http?.method==='OPTIONS')return out(204,null);try{const b=typeof e.body==='string'?JSON.parse(e.body):e.body||{};const totalSize=validate(b.files);const transferId=crypto.randomUUID();const expiresAt=new Date(Date.now()+604800000);const ownerId=e.requestContext?.authorizer?.claims?.sub||e.requestContext?.authorizer?.jwt?.claims?.sub||'guest';const files=b.files.map(f=>({fileName:f.fileName.trim(),fileSize:f.fileSize,contentType:f.contentType,objectKey:`uploads/${transferId}/${crypto.randomUUID()}`}));await ddb.send(new PutCommand({TableName:process.env.TABLE_NAME,Item:{transferId,ownerId,status:'pending',createdAt:new Date().toISOString(),expiresAt:expiresAt.toISOString(),ttl:Math.floor(expiresAt.getTime()/1000),totalSize,files,isBatch:true,downloadCount:0},ConditionExpression:'attribute_not_exists(transferId)'}));const uploads=await Promise.all(files.map(async f=>({fileName:f.fileName,uploadUrl:await getSignedUrl(s3,new PutObjectCommand({Bucket:process.env.UPLOADS_BUCKET,Key:f.objectKey,ContentType:f.contentType}),{expiresIn:900})})));return out(201,{success:true,data:{transferId,uploads,expiresAt:expiresAt.toISOString()}});}catch(x){console.error('batch-create failed',{name:x?.name});if(Array.isArray(x)&&x.length===3)return fail(x[0],x[1],x[2]);if(x instanceof SyntaxError)return fail(400,'INVALID_REQUEST','Malformed request body.');return fail(500,'INTERNAL_ERROR','Unable to create transfer.');}};
