const {DynamoDBClient}=require('@aws-sdk/client-dynamodb');
const {DynamoDBDocumentClient,GetCommand,UpdateCommand}=require('@aws-sdk/lib-dynamodb');
const {S3Client,GetObjectCommand}=require('@aws-sdk/client-s3');
const {getSignedUrl}=require('@aws-sdk/s3-request-presigner');
const ddb=DynamoDBDocumentClient.from(new DynamoDBClient({}));
const s3=new S3Client({});
const headers=()=>({'Access-Control-Allow-Origin':process.env.ALLOWED_ORIGIN,'Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization','Content-Type':'application/json'});
const out=(s,b)=>({statusCode:s,headers:headers(),body:JSON.stringify(b)}),fail=(s,c,m)=>out(s,{success:false,error:{code:c,message:m}}),safe=v=>String(v||'download').replace(/[\r\n"\\/]/g,'_').slice(0,180)||'download';
exports.handler=async e=>{if(e?.requestContext?.http?.method==='OPTIONS')return out(204,null);try{const id=e?.pathParameters?.id;if(!id||!/^[0-9a-f-]{36}$/i.test(id))return fail(400,'INVALID_TRANSFER_ID','Invalid transfer ID.');const item=(await ddb.send(new GetCommand({TableName:process.env.TABLE_NAME,Key:{transferId:id}}))).Item;if(!item)return fail(404,'TRANSFER_NOT_FOUND','Transfer not found.');if(item.expiresAt&&Date.parse(item.expiresAt)<=Date.now())return fail(410,'TRANSFER_EXPIRED','Transfer expired.');if(item.status!=='ready')return fail(409,'TRANSFER_NOT_READY','This transfer is not ready for download.');const key=item.isBatch?item.zipKey:item.objectKey;if(!key||!((item.isBatch&&key===`zips/${id}.zip`)||(!item.isBatch&&key.startsWith('uploads/'))))return fail(500,'INVALID_STORAGE_REFERENCE','Transfer storage metadata is invalid.');const fileName=safe(item.isBatch?`CloudDrop-${id}.zip`:item.originalFileName);const downloadUrl=await getSignedUrl(s3,new GetObjectCommand({Bucket:process.env.UPLOADS_BUCKET,Key:key,ResponseContentDisposition:`attachment; filename="${fileName}"`}),{expiresIn:300});await ddb.send(new UpdateCommand({TableName:process.env.TABLE_NAME,Key:{transferId:id},UpdateExpression:'ADD downloadCount :one',ExpressionAttributeValues:{':one':1}}));return out(200,{success:true,data:{downloadUrl,fileName,fileSize:item.isBatch?item.archiveSize||item.totalSize:item.fileSize,fileCount:item.isBatch?(Array.isArray(item.files)?item.files.length:1):1,expiresAt:item.expiresAt}});}catch(x){console.error('get-transfer failed',{name:x?.name});return fail(500,'INTERNAL_ERROR','Unable to prepare download.');}};
