const {DynamoDBClient}=require('@aws-sdk/client-dynamodb');
const {DynamoDBDocumentClient,PutCommand}=require('@aws-sdk/lib-dynamodb');
const {S3Client,PutObjectCommand}=require('@aws-sdk/client-s3');
const {getSignedUrl}=require('@aws-sdk/s3-request-presigner');
const crypto=require('crypto');
const ddb=DynamoDBDocumentClient.from(new DynamoDBClient({}));const s3=new S3Client({});
const MAX_FILE_SIZE=2*1024*1024*1024;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization'};
const out=(status,body)=>({statusCode:status,headers:{...cors,'Content-Type':'application/json'},body:JSON.stringify(body)});
exports.handler=async event=>{try{if(event.httpMethod==='OPTIONS')return out(204,'');const body=JSON.parse(event.body||'{}');const fileName=String(body.fileName||'').trim();const fileSize=Number(body.fileSize);const contentType=String(body.contentType||'application/octet-stream').slice(0,200);if(!fileName||fileName.length>255||!Number.isSafeInteger(fileSize)||fileSize<1||fileSize>MAX_FILE_SIZE)return out(400,{error:'Invalid file metadata'});const transferId=crypto.randomUUID();const objectKey=`uploads/${transferId}/${crypto.randomUUID()}`;const expiresAt=new Date(Date.now()+7*86400000);await ddb.send(new PutCommand({TableName:process.env.TABLE_NAME,Item:{transferId,objectKey,originalFileName:fileName,fileSize,contentType,status:'pending',createdAt:new Date().toISOString(),expiresAt:expiresAt.toISOString(),ttl:Math.floor(expiresAt.getTime()/1000),downloadCount:0,ownerId:event.requestContext?.authorizer?.claims?.sub||'guest'}}));const uploadUrl=await getSignedUrl(s3,new PutObjectCommand({Bucket:process.env.UPLOADS_BUCKET,Key:objectKey,ContentType:contentType}),{expiresIn:900});return out(200,{transferId,uploadUrl});}catch(error){console.error('create-transfer',error);return out(500,{error:'Internal server error'});}};
